### ISSUE TITLE
Node already doing transcoding can't also play stream

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-swarm#10]
<a href="https://github.com/dob"><img src="https://avatars3.githubusercontent.com/u/10389?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dob](https://github.com/dob)**
_Wednesday Mar 01, 2017 at 16:12 GMT_
_Originally opened as https://github.com/livepeer/go-ethereum/issues/41_

----

The `HandlePlay` function in the protocol doesn't work on a node that's already transcoding or relaying the stream. We think the reason is that it's already emptying the channel with the stream packets to transcode or relay, so when the handleplay function tries to copy from that channel there's nothing there. Instead, when we receive packets on a node, we should see if it's also trying to consume and if so write the packets to both the transcoding/relaying channel and then consuming channel.

**Comment by ericxtang** [comment]
This is solved by the stream / subscription model.
