### ISSUE TITLE
go get from README gives 'cannot find package "github.com/ethereum/go-ethereum/logger/glog"'

### ISSUE THREAD

**Issue by pgorsira** [livepeer/livepeer-swarm#24]
When running the "fetch and build the livepeer node" step of the Installation section from the README, it errors out:

```
$ go get github.com/livepeer/go-livepeer/cmd/livepeer
package github.com/ethereum/go-ethereum/logger/glog: cannot find package "github.com/ethereum/go-ethereum/logger/glog" in any of:
	/usr/local/Cellar/go/1.7.5/libexec/src/github.com/ethereum/go-ethereum/logger/glog (from $GOROOT)
	/Users/pgorsira/Projects/go/src/github.com/ethereum/go-ethereum/logger/glog (from $GOPATH)
```

Appears the cause is go-ethereum [switching](https://github.com/ethereum/ethash/issues/91) from glog to log15 [about a month ago](https://github.com/ethereum/go-ethereum/commit/0a63c3e3625e9f5e18f6c2a95934a37b1dcac6c7). You [can see](https://github.com/ethereum/go-ethereum) that the `logger` package is no longer available and has been replaced by `log`.

**Comment by pgorsira** [comment]
As a quick fix, I manually cloned https://github.com/livepeer/go-ethereum into my go workspace, moved `src/github.com/livepeer/go-ethereum` to `src/github.com/ethereum/go-ethereum`,  and re-ran the `go get` from above. This worked.

I suspect a longer term solution would be to update the logging statements in `go-livepeer` to use the new log15-based logger that's implemented in the current version of go-ethereum. Does that seem appropriate?

**Comment by dob** [comment]
Go-ethereum should be vendored in the /vendor dir, so I'm surprised this happened. I'll investigate. Thanks.

**Comment by dob** [comment]
Fixed via this commit to [LPMS](http://github.com/livepeer/lpms): 
 <https://github.com/livepeer/lpms/commit/fed5e0d9ee1b3e16e11fc963a99f01ab3f086025>
It was accidentally referencing go-ethereum/glog when it should have been importing golang/glog. LPMS isn't meant to have any dependencies on ethereum.
