### ISSUE TITLE
Stop HLS Streaming

### ISSUE THREAD

**Issue by ericxtang** [livepeer/livepeer-swarm#27]
When a HLS consumer stops, we don't have a sure way of detecting it.  Need to build some heuristics-based approach in the player so we can tell the upstream peer to stop streaming video.

**Comment by dob** [comment]
Hmm, maybe since HLS is based upon polling a constantly updated playlist,
we can take advantage of that. Maybe a node constantly polls upstream for a
playlist message, and then requests the segments one-by-one. I think this
could introduce some additional latency, but it could work.

**Comment by ericxtang** [comment]
Solved by creating a HLSUnsubscribeWorker in mediaserver.go.  It keeps track of the last time a stream is requested, and unsubscribes when it's past 10 seconds.
