### ISSUE TITLE
Add a transcoding request message type

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-swarm#3]
<a href="https://github.com/dob"><img src="https://avatars3.githubusercontent.com/u/10389?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dob](https://github.com/dob)**
_Friday Jan 27, 2017 at 19:44 GMT_
_Originally opened as https://github.com/livepeer/go-ethereum/issues/5_

----

The transcoding request should route to the "correct node" as determined by the network proximity rules. That node should accept the transcoding job, join the channel, consume the input, do a trivial transcoding operation on it (right now I think it should be a no-op), and then publish the output on a new channel. It should report this channel id back to the requester so they can be aware of it and advertise it if they'd like.

We'll add the actual transcoding in a media server integration in a subsequent issue.

**Comment by dob** [comment]
<a href="https://github.com/ericxtang"><img src="https://avatars3.githubusercontent.com/u/345743?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ericxtang](https://github.com/ericxtang)**
_Friday Feb 17, 2017 at 22:33 GMT_

----

Finished the first iteration. Next step - support transcode request into network + multiple streams available within network. There are a few options here, @dob let's talk about it on Monday.

**Comment by dob** [comment]
<a href="https://github.com/ericxtang"><img src="https://avatars3.githubusercontent.com/u/345743?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ericxtang](https://github.com/ericxtang)**
_Wednesday Feb 22, 2017 at 17:55 GMT_

----

![img_3285](https://cloud.githubusercontent.com/assets/345743/23224938/34c69c60-f8fe-11e6-8b99-3a46d2964117.JPG)

**Comment by ericxtang** [comment]
Code in hls branch.
