### ISSUE TITLE
HLS stream should listen for a "close" event, and close the channel properly.

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-swarm#5]
<a href="https://github.com/ericxtang"><img src="https://avatars3.githubusercontent.com/u/345743?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericxtang](https://github.com/ericxtang)**
_Friday Feb 17, 2017 at 22:29 GMT_
_Originally opened as https://github.com/livepeer/go-ethereum/issues/24_

----

Similar to RTMP, HLS should close the channel when the publisher stops.

**Comment by ericxtang** [comment]
Channel now closes after publisher stops.
